### ISSUE TITLE
The markdown file is not displayed well.

### ISSUE THREAD

**Issue by kimlimjustin** [vlang/gitly#105]
Hello, I recently tried Gitly and it looks very nice. However, it seems that markdown is not supported in Gitly recently. Gitly will be much nicer if markdown is supported in GitLy, especially for the `README.md` file. Thanks.
![Attachment](https://user-images.githubusercontent.com/61906684/102234697-2100b880-3f24-11eb-9b13-1c606f3ae71a.png)

**Comment by LouisSchmieder** [comment]
We've removed it because the lib is to large, but it will be fixed

**Comment by peteole** [comment]
This should be solved now. However code blocks are displayed strangely if the code is too long and syntax highlighting would be a nice bonus.

**Comment by walkingdevel** [comment]
Fixed in #206
