### ISSUE TITLE
Repositories can have the same name

### ISSUE THREAD

**Issue by Not-Nik** [vlang/gitly#111]
It's in the name. There is no warning, but the repositories aren't really seperate either. Creating a repository from a GitHub repo, with an already existing name apparently causes the clone process to fail. Commits are still displayed properly, but files aren't.
Attached are some images detailing how it exactly looks like.
<img width="241" alt="Screen Shot 2020-12-30 at 10 50 25 pm" src="https://user-images.githubusercontent.com/32980656/103383033-88f0fa80-4af1-11eb-808d-8010493b716c.png">
<img width="1053" alt="Screen Shot 2020-12-30 at 10 50 34 pm" src="https://user-images.githubusercontent.com/32980656/103383035-8a222780-4af1-11eb-83f2-37ee61f5f586.png">
<img width="1055" alt="Screen Shot 2020-12-30 at 10 50 46 pm" src="https://user-images.githubusercontent.com/32980656/103383037-8ababe00-4af1-11eb-91df-16cef6cfd8ce.png">

**Comment by LouisSchmieder** [comment]
Also fixed now, thanks for the report
