### ISSUE TITLE
Bad link to `/examples` folder in vlang repo

### ISSUE THREAD

**Issue by jxxp9** [vlang/gitly#141]
go here: 
http://gitly.org/medvednikov/v/blob/master/examples/process/execve.v
and click on "examples", you get here
http://gitly.org/medvednikov/v/tree//examples
which is an invalid link, we get `404 Not Found`

**Comment by shiipou** [comment]
Look like it just miss the branch name in the URL
http://gitly.org/medvednikov/v/tree/master/examples

**Comment by walkingdevel** [comment]
Fixed in #168
