### ISSUE TITLE
Current Gitly installation is broken

### ISSUE THREAD

**Issue by ice0** [vlang/gitly#162]
https://gitly.org/alex/vlang
![Screenshot_35](https://user-images.githubusercontent.com/5604544/167065828-7d23478c-7287-493a-8986-7e2370409c33.png)

**Comment by dumblob** [comment]
I would second this as now when V tries to catch attention of wider public by having `-autofree` by default, new incomers will want to see and "feel" it in action. And Gitly is one of the best opportunities for this IMHO.

**Comment by Cactusinhand** [comment]
https://gitly.org/alex/vlang doesn't work.

**Comment by JalonSolov** [comment]
That's because that isn't a valid link to a project.  Where did people find that?

Yes, it should tell you it's not a valid project, but that's a different issue from not working at all.

**Comment by EdJoPaTo** [comment]
Thats where the link on the main page ends up.

```html
<a href="/alex/vlang">gitly.org/vlang/v</a>
```

Copying the text of the link (https://gitly.org/vlang/v) directly ends up at 404 too so its not correct either?

**Comment by JalonSolov** [comment]
Those definitely need to be fixed.

**Comment by rilysh** [comment]
Any updates on this? Since there's no fix has been applied yet.

**Comment by medvednikov** [comment]
Yes, I’m working on it right now. Today (sep 4) it will be live.

**Comment by medvednikov** [comment]
Done:

https://gitly.org/alex/v
