### ISSUE TITLE
Javascript code appears 

### ISSUE THREAD

**Issue by dhonx** [vlang/gitly#17]
![2020-06-28_23-32](https://user-images.githubusercontent.com/17797740/85952158-fb91e980-b999-11ea-8e47-8883982e27aa.png)

**Comment by elimisteve** [comment]
Fixed in https://github.com/LouisSchmieder/gitly/commit/002f41f17ba4d86aadd87d6238285fdc53581889

**Comment by elimisteve** [comment]
I believe the longer-term fix will come from a bug fix in vweb
