### ISSUE TITLE
Deletion of Repositories does not work

### ISSUE THREAD

**Issue by SurmanPP** [vlang/gitly#204]
```html
<form action="/Surman/libtccv" method="delete">
		<input type="text" name="verify" placeholder="Type your repo path username/reponame" required="">
		<input type="submit" value="Delete repo">
</form>
```
Is invalid as DELETE is not a valid method for html forms. Invalid values for the method result in GET. Thus it can't work.

**Comment by JalonSolov** [comment]
DELETE is a valid http request method, same as GET, POST, PATCH, etc.

However, only GET and POST are valid for forms, even in HTML5.
