### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [vlang/gitly#230]
Hi everyone.

*I want to help, but I want to know if this project is active. Is this project active?*

**Comment by JalonSolov** [comment]
Yes, it is active.  Look at the commit history.

**Comment by JalonSolov** [comment]
![image](https://user-images.githubusercontent.com/37967083/206329845-8b6955d3-681d-4701-8003-0141bdae6a34.png)

That is the gitly page... see the word `commits`?  Click on it, and it will show the commit history.

**Comment by Larpon** [comment]
That's very AI of you to do, thanks!

**Comment by Larpon** [comment]
Do not worry
