### ISSUE TITLE
gitly.org 404

### ISSUE THREAD

**Issue by Plawn** [vlang/gitly#239]
The content of the files is 404 on the v repo as of now

**Comment by meichengg** [comment]
The problem persists till now.

![image](https://user-images.githubusercontent.com/25204246/217146420-d549ab12-52a8-4e1f-a086-7975165e15c1.png)

**Comment by aerphanas** [comment]
the problem is still there

![Screenshot from 2023-02-09 08-58-22](https://user-images.githubusercontent.com/61340494/217697479-2b839606-d6c5-4ae7-a130-d594d89103bf.png)

**Comment by aerphanas** [comment]
@Plawn look like the website is fixed now

**Comment by Plawn** [comment]
yay
