### ISSUE TITLE
software licensing question: plugin licensing, gitly add-on

### ISSUE THREAD

**Issue by ghost** [vlang/gitly#240]
Hello.

I would like to know something technical: plugin licensing, gitly add-on. If the gitly platform is gplv3 licensed, if I create an add-on or plugin on gitly. Do I have to include gplv3 licensing also in the addon and plugin?

**Comment by rusteroobs** [comment]
> I would like to know something technical: plugin licensing, gitly add-on. If the gitly platform is gplv3 licensed, if I create an add-on or plugin on gitly. Do I have to include gplv3 licensing also in the addon and plugin?

I think plugins don't depend on the language itself.
