### ISSUE TITLE
Unable to authorize if GitHub profile has no public email

### ISSUE THREAD

**Issue by medvednikovonelove** [vlang/gitly#84]
Currently you can only authorize on gitly if your GitHub profile has public email.

**Steps to reproduce:**

1. Open your GitHub profile settings by clicking Settings menu in profile.
2. Open "Profile" tab
3. Choose "Select a verified email to display" in select labelled as "Public email" 
![image](https://user-images.githubusercontent.com/67797114/87657800-21323780-c77d-11ea-83e4-637569f09d12.png)
4. Try to authorize on gitly.org

**Expected results:**
You should authorize and your account name should be displayed in header.

**Actual results:**
Gitly just redirects you on index page, no account name displayed.

If you try to repeat all the steps above, but select your email instead:
![image](https://user-images.githubusercontent.com/67797114/87658033-73735880-c77d-11ea-8ba7-c83a9ebf7c2b.png)
In this case authorization is successful.

**Possible solution**
You should try to identify users with unique user id github API provides, not email, if this is possible.

_Note_
You can check if user has public email by visiting its profile page on GitHub. For users with public email it is displayed there.

**Comment by JalonSolov** [comment]
At the very least, it would be good if gitly told you it couldn't register you because it couldn't find a public email - that way you at least know why it was sending you back to the index page.

**Comment by medvednikov** [comment]
Fixed.
